steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/n8n',
        '.'
      ]

images:
  - 'gcr.io/$PROJECT_ID/n8n'

# Optional: Deploy directly to Cloud Run after build
# substitutions:
#   _SERVICE_NAME: n8n
#   _REGION: us-central1
# steps:
#   - name: 'gcr.io/cloud-builders/gcloud'
#     args:
#       [
#         'run', 'deploy', '$_SERVICE_NAME',
#         '--image', 'gcr.io/$PROJECT_ID/n8n',
#         '--platform', 'managed',
#         '--region', '$_REGION',
#         '--allow-unauthenticated'
#       ]
